### ISSUE TITLE
running error when executing train.py

### ISSUE THREAD

**Issue by amiltonwong** [edwardzhou130/PolarSeg#1]
Hi, @edwardzhou130 ,

Thanks for releasing the package. I had followed the requirement.txt to install the required packages. However, when I run `python train.py`, I got the following error:

```
(pytorch1.3) root@milton-ThinkCentre-M93p:/data/code10/PolarSeg# python train.py 
/data/code10/PolarSeg/network/ptBEV.py:161: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float32, 2d, A), array(float32, 2d, A))
  pairwise_distance = sum_vec + np.transpose(sum_vec) - 2*np.dot(xyz, np.transpose(xyz))
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/targets/linalg.py", line 60, in ensure_blas
    import scipy.linalg.cython_blas
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/scipy/fft/__init__.py", line 81, in <module>
    from ._helper import next_fast_len
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/scipy/fft/_helper.py", line 4, in <module>
    from . import _pocketfft
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/scipy/fft/_pocketfft/basic.py", line 8, in <module>
    from . import pypocketfft as pfft
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-36m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/errors.py", line 717, in new_error_context
    yield
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 288, in lower_block
    self.lower_inst(inst)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 360, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 534, in lower_assign
    return self.lower_expr(ty, value)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 999, in lower_expr
    res = self.lower_call(resty, expr)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 791, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 970, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/targets/base.py", line 1146, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/targets/base.py", line 1176, in wrapper
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/targets/linalg.py", line 528, in dot_2
    ensure_blas()
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/targets/linalg.py", line 62, in ensure_blas
    raise ImportError("scipy 0.16+ is required for linear algebra")
ImportError: scipy 0.16+ is required for linear algebra

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from network.ptBEV import ptBEVnet
  File "/data/code10/PolarSeg/network/ptBEV.py", line 153, in <module>
    @nb.jit('b1[:](f4[:,:],i4)',nopython=True,cache=True)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/decorators.py", line 200, in wrapper
    disp.compile(sig)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler.py", line 331, in compile_extra
    return self._compile_bytecode()
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler.py", line 393, in _compile_bytecode
    return self._compile_core()
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler.py", line 373, in _compile_core
    raise e
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler.py", line 364, in _compile_core
    pm.run(self.state)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler_machinery.py", line 347, in run
    raise patched_exception
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/typed_passes.py", line 407, in run_pass
    NativeLowering().run_pass(state)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/typed_passes.py", line 349, in run_pass
    lower.lower()
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 195, in lower
    self.lower_normal_function(self.fndesc)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 248, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 273, in lower_function_body
    self.lower_block(block)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/lowering.py", line 288, in lower_block
    self.lower_inst(inst)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/errors.py", line 725, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/root/anaconda3/envs/pytorch1.3/lib/python3.6/site-packages/numba/six.py", line 669, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
scipy 0.16+ is required for linear algebra

File "network/ptBEV.py", line 161:
def nb_greedy_FPS(xyz,K):
    <source elided>
        sum_vec[j,0] = np.sum(xyz_sq[j,:])
    pairwise_distance = sum_vec + np.transpose(sum_vec) - 2*np.dot(xyz, np.transpose(xyz))
    ^

[1] During: lowering "$92.15 = call $92.9(xyz, $92.14, func=$92.9, args=[Var(xyz, ptBEV.py:155), Var($92.14, ptBEV.py:161)], kws=(), vararg=None)" at /data/code10/PolarSeg/network/ptBEV.py (161)

```

It seems that my scipy  is conflicted with numba. Could you give any hints on solving it? Also, please give corresponding version for the packages mentioned in `requirements.txt`

My installed packages are:
torch-scatter: 2.0.4
scipy: 1.4.1
numba: 0.47.0

THX!

**Comment by YangZhang4065** [comment]
Hi @amiltonwong ,

Thank you for reporting this issue and being interested in our project. It seems the error is not caused by a conflict between numba and scipy or anything on the python end but rather missing libstdc++.

libstdc++.so.6: version GLIBCXX_3.4.22 is found missing when numba attempt to `import scipy.linalg.cython_blas`. This is of course likely caused by an outdated libstdc++6. You probably want to make sure you have the current libstdc++ by doing 

```shell
sudo apt-get update
sudo apt-get install libstdc++6
sudo apt-get install --only-upgrade libstdc++6
```

 in terminal. Then you can try  `import scipy.linalg.cython_blas` again in Python to see if the scipy is able to find the libstdc++6.

Let me know how it turns out.

**Comment by amiltonwong** [comment]
@YangZhang4065 ,

Thanks a lot for your reply. I finally figure it out that the conflicts comes from torch-scatter and pytorch. I reinstalled pytorch to 1.4.0 and the latest version of torch-scatter again. And the problem is fixed.
