### ISSUE TITLE
RuntimeError: max_pool2d_with_indices_out_cuda_frame failed

### ISSUE THREAD

**Issue by shuangjiexu** [edwardzhou130/PolarSeg#4]
Thanks first for the excellent work!

I have run the polar network and it works well. But when I run the traditional network for comparison, there comes a RuntimeError:

```Traceback (most recent call last):
  File "train.py", line 195, in <module>
    main(args)
  File "train.py", line 164, in main
    outputs = my_model(train_pt_fea_ten,train_grid_ten)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shuangjie/Projects/dev/Rand-LA/ref/PolarSeg/network/ptBEV.py", line 139, in forward
    net_return_data = self.BEV_model(out_data)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shuangjie/Projects/dev/Rand-LA/ref/PolarSeg/network/BEV_Unet.py", line 19, in forward
    x = self.network(x)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shuangjie/Projects/dev/Rand-LA/ref/PolarSeg/network/BEV_Unet.py", line 46, in forward
    x4 = self.down3(x3)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shuangjie/Projects/dev/Rand-LA/ref/PolarSeg/network/BEV_Unet.py", line 159, in forward
    x = self.mpconv(x)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 141, in forward
    self.return_indices)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/_jit_internal.py", line 181, in fn
    return if_false(*args, **kwargs)
  File "/home/shuangjie/.virtualenvs/polar-seg/lib/python3.6/site-packages/torch/nn/functional.py", line 488, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: max_pool2d_with_indices_out_cuda_frame failed with error code 0
```

Looking forward for your reply.

**Comment by shuangjiexu** [comment]
Seem to be a Pytorch bug, add `x = x.contiguous()` in the `down` module in BEV_Unet.py fix the problem. Still curious about why.
