### ISSUE TITLE
training index out of bound error

### ISSUE THREAD

**Issue by varun365** [edwardzhou130/PolarSeg#9]
Hi @edwardzhou130 
Thanks for your effort on this.
I tried to start the training with semantic kitti seq 04 with default arguments - got the following 

Namespace(check_iter=4000, data_dir='data', grid_size=[480, 360, 32], model='polar', model_save_path='./SemKITTI_PolarSeg.pt', train_batch_size=2, val_batch_size=2)
  0%|                                                                                                                    | 0/136 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main(args)
  File "train.py", line 118, in main
    val_vox_label = SemKITTI2train(val_vox_label)
  File "train.py", line 39, in SemKITTI2train
    return SemKITTI2train_single(label)
  File "train.py", line 44, in SemKITTI2train_single
    label[remove_ind] = 255
IndexError: index 17592186044634 is out of bounds for dimension 2 with size 360

So I tried changing the batch & val_size to 1 and grid size to [320,240,32]

Namespace(check_iter=4000, data_dir='data', grid_size=[320, 240, 32], model='polar', model_save_path='./SemKITTI_PolarSeg.pt', train_batch_size=1, val_batch_size=1)
  0%|                                                                                                                    | 0/271 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main(args)
  File "train.py", line 118, in main
    val_vox_label = SemKITTI2train(val_vox_label)
  File "train.py", line 39, in SemKITTI2train
    return SemKITTI2train_single(label)
  File "train.py", line 44, in SemKITTI2train_single
    label[remove_ind] = 255
IndexError: index 227 is out of bounds for dimension 0 with size 1

Can you help me figure this. Thanks in advance

**Comment by edwardzhou130** [comment]
My guess is something goes wrong in ``SemKITTI2train_single``:
https://github.com/edwardzhou130/PolarSeg/blob/73488e8fe3ea9505d2822232ac5e814530c3c724/train.py#L41-L45
The shape of ``remove_ind`` and ``label`` should be the same, but somehow it gets changed in this function.
